import Head from "next/head";
import styles from "../styles/Home.module.css";
import NFTView from "../components/NFTView";
import { headRange, backgroundRange, legsRange, torsoRange } from "../util";

export default function Home() {
  const randomElement = (array: any[]) => {
    return array[Math.floor(Math.random() * array.length)];
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Monster Maker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Monster Maker</h1>

        <NFTView
          bgIndex={randomElement(backgroundRange())}
          headIndex={randomElement(headRange())}
          legsIndex={randomElement(legsRange())}
          torsoIndex={randomElement(torsoRange())}
        />
      </main>
    </div>
  );
}
