import Head from "next/head";
import styles from "../styles/Home.module.css";
import NFTView from "../components/NFTView";
import { headRange, backgroundRange, legsRange, torsoRange } from "../util";
import Image from 'next/image'

export default function Home() {
  const randomElement = (array: any[]) => {
    return array[Math.floor(Math.random() * array.length)];
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Monster Maker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <h1 className={styles.title}>Monster Maker</h1> */}

        <div style={{display: 'flex', flexDirection: 'column', gap: '50px'}}>
        <Image src="/images/logo.png" alt="logo" height="100" width="268" objectFit="scale-down" />

        <NFTView
          bgIndex={randomElement(backgroundRange())}
          headIndex={randomElement(headRange())}
          legsIndex={randomElement(legsRange())}
          torsoIndex={randomElement(torsoRange())}
        />
        </div>
      </main>
    </div>
  );
}
